### ISSUE TITLE
Req.route.path invalid

### ISSUE THREAD

**Issue by talvane** [gladchinda/joi-schema-validation-sourcecode#2]
Hi, @gladchinda.

I would first like to thank you for the excellent example / tutorial of using lib Joi.
I took your example and had to change the line below:
https://github.com/gladchinda/joi-schema-validation-sourcecode/blob/00e4a470a3c2cbce98c23ff658fc01c31bc80573/middlewares/SchemaValidator.js#L23

For:
`const route = req.path;`

Would you accept a PR of mine to test?

Tks.

**Comment by gladchinda** [comment]
Hi @talvane 

Thanks for taking out time to go through this code example and I am really glad that you found it useful. There is however a reason why I chose to reference the route using `req.route.path` as opposed to using just `req.path`.

The reason being for routes that also have route parameters. Consider this route:

```js
app.post('/api/v1/:collection', function (req, res, next) {
  // route handling logic here...
});
```

The following table shows the results of `req.route.path` and `req.path` for some request paths that match the above route.

| `req.path` | `req.params.collection` | `req.route.path` |
|---|---|---|
| `/api/v1/authors` | `authors` | `/api/v1/:collection` |
| `/api/v1/posts` | `posts` | `/api/v1/:collection` |
| `/api/v1/comments` | `comments` | `/api/v1/:collection` |
| `/api/v1/subscribers` | `subscribers` | `/api/v1/:collection` |

It becomes very clear why `req.route.path` is being used as the basis for defining a validation schema to match multiple target paths, as opposed to creating separate schemas for each path. However, if the requirement of the application is that a separate schema be created for each path, then the middleware can be modified as seems fit.

**Comment by talvane** [comment]
Hey @gladchinda.

I understood, it makes perfect sense even that way, I hadn't thought.
Tks for the feedback. :)
